name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go
        with:
          go-version: '1.26.x'
      - uses: gofmt check
        run: test -z "$(gofmt -l $(find . -name '*.go'))"
      - name: go test
        run: go test ./...